### ISSUE TITLE
When I use this command, Image not showing

### ISSUE THREAD

**Issue by taz1208** [peiffer-innovations/websafe_svg#15] opened 2020-12-09 01:26 UTC
I use this `flutter run -d chrome --release --dart-define=FLUTTER_WEB_USE_SKIA=true`
But '.svg' files not working
Related Link : https://github.com/flutter/flutter/issues/71627#issuecomment-740320874

**Comment by jpeiffer** [comment] 2020-12-13 22:55
There's not enough info to triage this issue.  Can you provide what version of flutter, what browser, what SVG, etc.  Also, does it work w/o the FLUTTER_WEB_USE_SKIA flag?

**Comment by taz1208** [comment] 2020-12-14 01:57
Here is my `doctor -v`
```
[✓] Flutter (Channel master, 1.25.0-4.0.pre, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-KR)
    • Flutter version 1.25.0-4.0.pre at /Users/taz/Documents/flutter_channels/flutter_mastar
    • Framework revision a7f5fd5360 (3 days ago), 2020-11-30 13:14:13 +0100
    • Engine revision 20caf54969
    • Dart version 2.12.0 (build 2.12.0-76.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/taz/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = /Users/taz/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 87.0.4280.88

• No issues found!
```

and browse is Chrome,

It only happens when I use `FLUTTER_WEB_USE_SKI`

**Comment by jpeiffer** [comment] 2020-12-15 03:07
In that case, the issue is with the core Flutter and my ability to help is pretty limited.

Here's how this plugin works...  When you're running in a web context, the plugin will get the SVG, encode the SVG into a data URI, and then passes that data URI to Flutter's `Image.network`.  It's Flutter's own `Image.network` that renders the SVG for the browser (or in this case... doesn't).

If you can give me a full working example that shows the issue, I can champion / update the defect for you.  I had luck getting a separate Firefox issue fixed by the Flutter team this way.  Absent that, there's not much I can do.

**Comment by tsinis** [comment] 2020-12-19 18:44
Hey @taz1208 if you are using `--dart-define=FLUTTER_WEB_USE_SKIA=true` flag, should use classic [flutter_svg package, which websafe_svg package uses anyway](https://github.com/peiffer-innovations/websafe_svg/blob/2cccc92fb9dddf05e2f9e0aeb9062d76fdb4dc71/pubspec.yaml#L12). Since [flutter_svg  supports web with Skia](https://github.com/dnfield/flutter_svg/issues/428#issuecomment-707292570).

**Comment by jpeiffer** [comment] 2020-12-22 02:06
Oooohhhh...  Can't say I'll mind retiring this plugin in favor of being able to use universal `flutter_svg`...  Look forward to that landing as the default.

**Comment by jpeiffer** [comment] 2020-12-22 02:08
@tsinis : Do you know if there's a way to detect if the web is running in SKIA mode or regular mode?  As a bridge, I'd be happy to update this plugin to fully utilize `flutter_svg` in SKIA mode but still fall back to `Image.network` when not in SKIA mode.

**Comment by tsinis** [comment] 2020-12-24 14:38
> @tsinis : Do you know if there's a way to detect if the web is running in SKIA mode or regular mode?  As a bridge, I'd be happy to update this plugin to fully utilize `flutter_svg` in SKIA mode but still fall back to `Image.network` when not in SKIA mode.

I didn't write a single word about you have to retire your package :). Web with SKIA enabled is too heavy for most Flutter devs. So your solution is useful. Anyways, in term of your question: you might want to check bool.fromEnvironment or String.fromEnvironment. You can read more about it at:

https://github.com/flutter/flutter_web/blob/master/docs/canvaskit.md

P.S. I've had a problems with Websafe SVG at dev/master channels in production, I mean it was working fine at my machine during development in debug/release/profile but running builded release version on local/online host didn't worked at all. I'll make small reproducible example later at the end of the month. Thank you for your great job anyways!

**Comment by muhleder** [comment] 2020-12-26 13:29
This should fix it https://github.com/muhleder/websafe_svg/commit/86b1eb374f38e7a140e563e2dba1d264224afd52 Not elegant code but it seems to work so long as the auto option isn't used.

FYI the dart define flag is being deprecated and it will be set with --web-renderer option instead. See https://github.com/flutter/engine/blob/master/lib/web_ui/lib/src/engine/canvaskit/initialization.dart and also https://github.com/flutter/engine/pull/21852



To support the auto option we'd need to check engine.useCanvasKit but I'm not sure if/how we can access engine from within flutter.

**Comment by jpeiffer** [comment] 2021-03-30 01:41
Sorry this one took so long.  Noticed today that the Flutter team resolved the root issue.  This is now fixed via:
https://pub.dev/packages/websafe_svg/versions/2.0.0-nullsafety.0

Unfortunately, it has to stay a pre-release version until `flutter_svg` releases Null Safety on Stable too.

**Closed as completed by jpeiffer** 2021-03-30 01:41 UTC
