### ISSUE TITLE
Error on Flutter 1.24.0-7+ version of Flutter

### ISSUE THREAD

**Issue by tsinis** [peiffer-innovations/websafe_svg#13] opened 2020-11-01 11:25 UTC
Hey @peiffer-innovations! Thanks for package, I'm just want to point you out, that after upgrade to latest master branch of Flutter SVGs showing error:
`Future<Codec>', but got one of type '_Future<Codec?>`

Perhaps we just can wait a little, so it would possibly be fixed on Flutter side till stable version 1.24 comes out, or you can check it by yourself. Thanks once more!

**Comment by jpeiffer** [comment] 2020-11-08 16:32
I cannot reproduce this.  I tried in `master` which is now `1.24.0-8.0.pre.147` as well as the `dev` channel which is currently `1.24.0-7.0.pre`.  Both ran just fine on iOS, Android, and Web for me.

Maybe it was already fixed in the `master` branch?

**Closed as completed by jpeiffer** 2020-11-08 16:32 UTC

**Comment by tsinis** [comment] 2020-11-08 22:17
Yeah thanks. Can confirm it's working fine again on 1.24.0-8!
