### ISSUE TITLE
Exception: Bad state: Future already completed

### ISSUE THREAD

**Issue by patmuk** [peiffer-innovations/websafe_svg#1] opened 2020-04-30 20:46 UTC
`flutter run -d chrome`  
shows the following error on startup:
```

════════ Exception caught by services library ══════════════════════════════════
The following StateError was thrown during a platform message response callback:
Bad state: Future already completed

When the exception was thrown, this was the stack
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 195:49  throw_
dart-sdk/lib/async/future_impl.dart 42:79                                     complete
packages/flutter/src/services/binding.dart 176:18                             <fn>
dart-sdk/lib/async/zone.dart 1374:10                                          runUnaryGuarded
lib/_engine/engine/window.dart 331:23                                         <fn>
...
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by services library ══════════════════════════════════
Bad state: Future already completed
════════════════════════════════════════════════════════════════════════════════```
etc.
running
```
flutter --version
Flutter 1.17.0 • channel beta • https://github.com/flutter/flutter.git
Framework • revision d3ed9ec945 (3 weeks ago) • 2020-04-06 14:07:34 -0700
Engine • revision c9506cb8e9
Tools • Dart 2.8.0 (build 2.8.0-dev.18.0 eea9717938)
```
All works fine, but the error message is distracting.

**Comment by lewooz** [comment] 2020-05-01 22:44
I am getting the same error aswell. Svg renders fine on the screen tough.

**Comment by patmuk** [comment] 2020-05-06 20:34
Yes, rendering was fine for me as well - the error was the only noticeable thing.

However, I implemented it differently now: As Browsers can render svg one only needs to point them to the resource. This can be done with `image.network(assets/yourdir/yourfile.svg)`.
For this to work the assets need to be located in /web/assets.
As we build the flutter app exclusively for web (our replacement for Gatsby) we did not need to make it work for a smartphone as well.  
I assume that this package does the same under the hood - only more powerful by taking care of the right path and having it compilable for devices and web.  
But the error message added too much pollution.

**Comment by jpeiffer** [comment] 2020-05-06 22:29
Thanks, I'll look into this.  I think I see the issue.  It's likely happening because the SVG widget is being rebuilt via a state update in a parent widget.

And you're correct, under the hood, this does do an `Image.network`, but only if there are no headers.  That's because `Image.network` can't send headers along.  A lot of mobile apps use headers to authorize images.  If headers are passed along, this makes a HTTP call to get the image, passes along the headers, then uses `Image.memory` by crafting a data URL.

**Comment by jpeiffer** [comment] 2020-05-29 03:36
I cannot seem to recreate this issue.  Can you provide an example that can?  From what I can tell, this may have been an internal Flutter issue and may be now resolved.

**Comment by jpeiffer** [comment] 2020-06-01 21:14
Closing issue as not reproducable.

**Closed as completed by jpeiffer** 2020-06-01 21:14 UTC
